project:
  type: website
  output-dir: docs

website:
  title: "An√°lisis del universo de D&D"
  navbar:
    left:
      - href: proyecto_final.qmd
        text: Inicio

format:
  html:
    theme: superhero
    toc: true
    toc-location: right
    smooth-scroll: true
    page-layout: article
lang: es
